package com.v2dawn.autotombstone.hook.tombstone.support;

object MethodEnum {
    const val systemMain ="systemMain"
    const val updateActivityUsageStats = "updateActivityUsageStats"
    const val deliverToRegisteredReceiverLocked = "deliverToRegisteredReceiverLocked"
    const val appNotResponding = "appNotResponding"
    const val startAnrConsumerIfNeeded = "startAnrConsumerIfNeeded"
    const val isAppForeground = "isAppForeground"
    const val add = "add"
    const val killServicesLocked = "killServicesLocked"
    const val setCurAdj = "setCurAdj"
    const val applyOomAdjLocked = "applyOomAdjLocked"
    const val getEnable = "getEnable"
    const val isFreezerSupported = "isFreezerSupported"
    const val setProcessFrozen = "setProcessFrozen"
    const val useFreezer = "useFreezer"
    const val computeOomAdjLSP = "computeOomAdjLSP"
    const val setOomAdj = "setOomAdj"
    const val clearAppWhenScreenOffTimeOutInNight = "clearAppWhenScreenOffTimeOutInNight"
    const val clearAppWhenScreenOffTimeOut = "clearAppWhenScreenOffTimeOut"
    const val clearUnactiveApps = "clearUnactiveApps"
    const val setMode = "setMode"
    const val setAppInactive = "setAppInactive"
    const val getAppStandbyBucket = "getAppStandbyBucket"
    const val setAppStandbyBucket = "setAppStandbyBucket"
    const val makePackageIdle = "makePackageIdle"
}
